name: sre-monitoring-prod

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

  # Run the workflow every 5 minutes (UTC time)
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: [x86]

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world! GitHub app is running successfully.
